Updated Icones section to add description sentences
alpescraft/alpescraft-2019 pull request #3
Opened 2019-05-01 11:22 UTC by vgallet

* split Icones sections into two parts: grid & description

2019-05-01 12:42 UTC, martinsson commented
Cette version me parait très bien. J'ai fait une petite suggestion sur une des formulations.

2019-05-01 18:34 UTC, martinsson commented on config.yml
> +                   nous souhaitons mettre l'accent sur les pratiques au délà des derniers frameworks
Pour mettre moins l'accent sur le manque des dernières technos, je propose cette formulation:

AlpesCraft est une conférence technique, agnostique aux technos.  Nous pensons que le plus important est de bien maîtriser les fondamentaux et d'apprendre les pratiques au delà des frame-works.

2019-05-02 17:23 UTC, vgallet commented on config.yml
> +                   nous souhaitons mettre l'accent sur les pratiques au délà des derniers frameworks
lgtm

2019-05-02 18:33 UTC, Ldoppea requested changes

2019-05-02 18:33 UTC, Ldoppea commented on config.yml
> +      - paragraph: "Nous pensons que le plus important est de bien maîtriser les fondamentaux et d'apprendre les pratiques au delà des frame-works"
Je ne suis pas sûr que frame-work existe, je préfère en un seul mot : framework
D'ailleurs tu l'utilise en un seul mot plus loin

2019-05-02 18:33 UTC, Ldoppea commented on config.yml
>      - title: "Découvrir"
Il faudrait indenter le contenu de `grid` pour concorder avec la convention yaml

2019-05-02 21:08 UTC, martinsson commented on config.yml
> +                   nous souhaitons mettre l'accent sur les pratiques au délà des derniers frameworks
parfait

2019-05-03 10:23 UTC, vgallet commented on config.yml
>      - title: "Découvrir"
yep, correction effectuée

2019-05-03 10:23 UTC, vgallet commented on config.yml
> +      - paragraph: "Nous pensons que le plus important est de bien maîtriser les fondamentaux et d'apprendre les pratiques au delà des frame-works"
yep, correction effectutée.

2019-05-03 10:43 UTC, merged