fix the navbar + small UI enhancements
alpescraft/alpescraft-2019 pull request #39
Opened 2022-05-25 11:56 UTC by jsulpis

- fix the navbar behaviour on all screen sizes (avoid flickers, overflow...)
- adjustments on the animations of the "back to top" button and the header

2022-05-26 08:44 UTC, vgallet commented
Hello, merci pour ta contribution Julien mais avec tes changements, la scrollbar ne se rétracte plus, c'est voulu ?

2022-05-26 08:47 UTC, vgallet requested changes

2022-05-26 08:47 UTC, vgallet commented on layouts/partials/footer.html
> +<button id="top-button" title="scroll to top" onclick="scrollToTop()">
pourquoi ajouter ce bouton ? Ce ajoute un petit trait noir comme sur l'image ci-dessous ?
![2022-05-26_10-43](https://user-images.githubusercontent.com/8947458/170453020-80b5e9b1-6b2e-46bc-ba60-dfcb5fb1b829.png)
?

2022-05-26 08:47 UTC, vgallet commented on layouts/partials/index/nav.html
> +          {{ range $previous := $.Site.Params.Previous }} {{ range $key, $value
atention hugo n'aime pas les sauts de lignes au milieu du range. Il faut inline le range

```suggestion
          {{ range $previous := $.Site.Params.Previous }} {{ range $key, $value := (index $.Site.Params.TitlesPrevious $previous) }}
```

2022-05-30 11:42 UTC, jsulpis commented
> Hello, merci pour ta contribution Julien mais avec tes changements, la navbar ne se rétracte plus, c'est voulu ?

Oui, quand il y a seulement les icônes on ne voit pas vers quoi les liens pointent

2022-05-30 11:42 UTC, jsulpis commented on layouts/partials/index/nav.html
> +          {{ range $previous := $.Site.Params.Previous }} {{ range $key, $value
✅

2022-05-30 11:43 UTC, jsulpis commented on layouts/partials/footer.html
> +<button id="top-button" title="scroll to top" onclick="scrollToTop()">
question de sémantique, une balise `<i>` n'est pas censée être cliquable. Dans ce cas c'est plutôt un bouton

2022-05-30 16:15 UTC, vgallet approved these changes

2022-05-30 16:15 UTC, merged